# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170324_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
